title = "Gitleaks Config"

[allowlist]
  description = "Allow placeholders and docs examples"
  regexes = [
    '''sk-proj-your[_a-zA-Z0-9-]*''',
    '''AIzaSy_your[_a-zA-Z0-9-]*''',
    '''postgresql://username:password@''',
    '''your_gemini_api_key_here''',
    '''your_openai_api_key_here''',
    '''your_clerk_secret_key_here''',
    '''vercel_blob_your_token_here''',
    '''vercel_blob_rw_your_token''',
    '''your_app_password''',
    '''generate_strong_random_32_chars_key''',
    '''change-me-token''',
  ]

# Exclude directories with vendored or generated content
[pathAllowlist]
  description = "Ignore generated build dirs and virtual env"
  paths = [
    ".next/",
    "node_modules/",
    "backend/.ok/",
  ]

