version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - NEXT_PUBLIC_API_URL=http://backend:5001
    depends_on:
      - backend
    volumes:
      - recordings_data:/app/recordings
    networks:
      - cognitive-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - STORAGE_PATH=/app/recordings
      - FLASK_ENV=production
    volumes:
      - recordings_data:/app/recordings
    networks:
      - cognitive-network

volumes:
  recordings_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./recordings

networks:
  cognitive-network:
    driver: bridge